### ISSUE TITLE
ImportError: No module named robotis_op_gazebo.darwin

### ISSUE THREAD

**Issue by brothaman** [ROBOTIS-OP/robotis_op_simulation#3]
followed all instructions( https://github.com/ROBOTIS-OP/robotis_op_documentation/wiki ) for installation and installed all repositories:

git clone https://github.com/ROBOTIS-OP/robotis_op_common.git
git clone https://github.com/ROBOTIS-OP/robotis_op_launch.git
git clone https://github.com/ROBOTIS-OP/robotis_op_simulation.git
git clone https://github.com/ROBOTIS-OP/robotis_op_teleop.git
git clone https://github.com/ROBOTIS-OP/robotis_op_moveit.git

added the repositories
ran catkin_make...

Now, going through the tutorials I encountered the error:

after running the command: `rosrun robotis_op_simulation_walking walker_demo`
it outputs:

```
Traceback (most recent call last):
  File "/home/username/catkin_ws/src/robotis_op_simulation/robotis_op_simulation_walking/scripts/walker_demo.py", line 4, in <module>
    from robotis_op_gazebo.darwin import Darwin
ImportError: No module named robotis_op_gazebo.darwin
```

I have looked through my entire system for the module named robotis_op_gazebo.py and found nothing.

Currently I'm using ROS Indigo.

**Comment by kdaun** [comment]
Hi,
I updated the wiki. You can start the walking node by calling
 `rosrun  robotis_op_simulation_walking walker.py` 

If more issues come up, feel free to ask ;-)

Regards,
Kevin
